import numpy as np
import pandas as pd

# You can also use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')
tables = pd.read_html("https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29")
#print (tables)
gdp_data = tables[3]
gdp_data.columns = ["Country/Territory", "UN_region", "IMF_Estimate", "IMF_Year", "World_Bank_Estimate", "World_Bank_Year","United_Nations_Estimate","United_Nations_Year"]
#print(gdp_data.head())
gdp_data.dropna(subset=[("Country/Territory")], inplace=True)
#print(gdp_data.head())
selected_columns = ["Country/Territory", "IMF_Estimate"]
new_data = gdp_data[selected_columns]
new_data = new_data.iloc[1:]
print(new_data.head(10))
